### ISSUE TITLE
FALLOC_FL_KEEP_SIZE is not declared in <fcntl.h>

### ISSUE THREAD

**Issue by Melkor-1** [mkerrisk/man-pages#40]
As per the man page, I have defined `_GNU_SOURCE` before the inclusion of `<fcntl.h>`:

```c
#include <stdio.h>

#define _GNU_SOURCE    /* For Linux's fallocate(). */
#define HAVE_FALLOCATE 1

#include <fcntl.h>

int main(void)
{
    printf("%d\n", FALLOC_FL_KEEP_SIZE);
}
```

which I compiled with:

```none
gcc-13 -std=gnu2x c.c
```

But this fails with:

```none
error: `FALLOC_FL_KEEP_SIZE` undeclared (first use in this function)
```

Some stats about the environment:

```none
OS: Linux Mint 21.2 x86_64
Kernel: 5.15.0-112-generic
GLIBC Version: GNU C Library (Ubuntu GLIBC 2.35-0ubuntu3.8) stable release 2.35
Compiler: gcc version 13.1.0 (Ubuntu 13.1.0-8ubuntu1~22.04)
```

Running `grep -r FALLOC_FL_KEEP_SIZE /usr/include` returned:

```none
/usr/include/linux/falloc.h:#define FALLOC_FL_KEEP_SIZE 0x01 /* default is extend size */
/usr/include/linux/falloc.h: * with fallocate. Flag FALLOC_FL_KEEP_SIZE should cause the inode
```

So they are present in `<linux/falloc.h>`. [StackOverflow](https://stackoverflow.com/a/78659243/20017547) says that the error is in the man page. And that `<fcntl.h>` doesn't provide any of the `FALLOC_...` constants.

**Comment by josephcsible** [comment]
There's no error in the man page. The error is in your code. You did `#define _GNU_SOURCE` after `#include <stdio.h>`, which the man page for `feature_test_macros` makes it clear that you're not allowed to do. Swap those two lines and your program will work fine.

**Comment by Melkor-1** [comment]
The problem is indeed with my code, _and some misguidance_. This issue is solved.
